#!/usr/bin/env python

import qbdpy
import IPython
import os
import subprocess
import sys


def main(script, params):
    path = list(p for p in qbdpy.__path__)[0]
    path = os.path.join(path, 'qbdpy._qbdi.so')

    env = os.environ.copy()
    env.update({
        'LD_PRELOAD': path,
        'QBDPY_SCRIPT': script,
    })

    p = subprocess.Popen(
        params,
        env=env,
    )
    p.wait()


if __name__ == '__main__':
    if len(sys.argv) < 3:
        print('Usage: {} script.py /path/to/target'.format(sys.argv[0]))
        exit()

    main(sys.argv[1], sys.argv[2:])

