#!/usr/bin/env python

import os
import re
import subprocess
import sys

import qbdpy


def find_lib():
    root = os.path.dirname(qbdpy.__file__)
    m = re.compile(r'_qbdi.*\.so')
    for fn in os.listdir(root):
        if m.match(fn):
            return os.path.join(root, fn)
    else:
        raise Exception('qbdpy: Couldn\'t find native library')


def main(script, params):
    if not os.path.isfile(script):
        print('qbdpy: Couldn\'t find script "{}"'.format(script))
        exit(1)

    so_path = find_lib()

    env = os.environ.copy()
    env.update({
        'LD_PRELOAD': so_path,
        'QBDPY_SCRIPT': script,
    })

    p = subprocess.Popen(
        params,
        env=env,
    )
    p.wait()


if __name__ == '__main__':
    if len(sys.argv) < 3:
        print('Usage: {} script.py /path/to/target'.format(sys.argv[0]))
        exit()

    main(sys.argv[1], sys.argv[2:])

